services:
  # Main Streamlit application
  app:
    build: .
    container_name: image-checker-suite
    volumes:
      # Mount code for hot-reloading in development
      - .:/app
      # Preserve Python cache
      - python-cache:/root/.cache
      # Persist output directories
      - ./grouped_output:/app/grouped_output
      - ./qc_overlays:/app/qc_overlays
      - ./review:/app/review
      - ./masks:/app/masks
      - ./temp:/app/temp
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    restart: unless-stopped
    command: streamlit run app.py

  # Development shell for testing and running scripts
  dev:
    build: .
    container_name: image-checker-dev
    volumes:
      - .:/app
      - python-cache:/root/.cache
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    command: /bin/bash
    profiles:
      - dev

volumes:
  python-cache:
